# Author: Frenz Louis C. Bautista
print("========================================")
print("\t\tEXPENSE TRACKER")
print("\tKnow where your money goes.")
print("========================================")
print("")
print("Welcome! This is your personal expense tracker.")
print("")
print("MAIN MENU")
print("  [1] Add an expense \t\t\t(coming soon)")
print("  [2] View all expenses \t\t(coming soon)")
print("  [3] Show total spent \t\t\t(coming soon)")
print("  [4] Exit \t\t\t\t(coming soon)")
print("")
print("----------------------------------------")
print("Made by: Frenz Louis C. Bautista | Installment 1")
print("========================================")
