# Author: Frenz Louis C. Bautista
print("========================================")
print("\t\tEXPENSE TRACKER")
print("\tKnow where your money goes.")
print("========================================")
print("")
print("Welcome! This is your personal expense tracker.")
print("")
print("MAIN MENU")
print("  [1] Add an expense \t\t\t(coming soon)")
print("  [2] View all expenses \t\t(coming soon)")
print("  [3] Show total spent \t\t\t(coming soon)")
print("  [4] Exit \t\t\t\t(coming soon)")
print("")
name = input("What's your name?: ")
print(f"Welcome, {name}!" + " Let's log two expenses.")
print("")
item1 = input("First expenses: ") 
amount1 = float(input("Amount: "))
item2 = input("First expenses: ") 
amount2 = float(input("Amount: "))
print("")
print("----------------------------------------")
print("SUMMARY")
print(f" - {item1}: \t${amount1}")
print(f" - {item2}: \t${amount2}")
total = amount1 + amount2
print(f"Total spent: \t${total}")
average = (amount1 + amount2) / 2
print(f"Average: \t${average}")
print("----------------------------------------")
print("Made by: Frenz Louis C. Bautista | Installment 2")
print("========================================")